export const SET_DISH = 'SET_DISH'
export const SET_DISH_SUCCESS = "SET_DISH_SUCCESS"
export const DISH_ADD = 'DISH_ADD'
export const DISH_REMOVE = 'DISH_REMOVE'
export const DISH_CHANGE = 'DISH_CHANGE'

export const TYPES_LOADING = 'TYPES_LOADING'
export const GET_TYPES_DISH = 'GET_TYPES_DISH'
export const ACTIVE_TYPE_DISH = 'ACTIVE_TYPE_DISH'

export const GET_STATUS = 'GET_STATUS'

export const SET_ORDERS = 'SET_ORDERS'
export const SET_ORDERS_SUCCESS = 'SET_ORDERS_SUCCESS'
export const ORDERS_ADD = 'ORDERS_ADD'
export const UPDATE_ORDERS = 'UPDATE_ORDERS'
export const ORDER_DELETE_DISH = 'ORDER_DELETE_DISH'
export const ORDER_ADD_DISH = 'ORDER_ADD_DISH'